### ISSUE TITLE
Compile problem with latest 12.2-release.

### ISSUE THREAD

**Issue by epasveer** [NVIDIA/cuda-gdb#14]
I grabbed the latest tarball after this morning's notice.  It fails to build in "gdbsupport".
```
make[3]: Entering directory '/nas/erniep/Development/cuda-gdb/cuda-gdb-cuda-toolkit-12.2-release/gdbsupport'
  CXX      agent.o
  CXX      btrace-common.o
  CXX      buffer.o
  CXX      cleanups.o
  CXX      common-debug.o
  CXX      common-exceptions.o
  CXX      common-inferior.o
  CXX      common-regcache.o
  CXX      common-utils.o
  CXX      environ.o
  CXX      errors.o
  CXX      event-loop.o
In file included from event-loop.cc:42:
./../gdb/cuda/cuda-notifications.h:22:10: fatal error: cudadebugger.h: No such file or directory
   22 | #include "cudadebugger.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
```
Here's the build command I used:
```
$  ./configure --prefix=/usr/local/cuda-12.2
$  make
```
I can't find "cudadebugger.h" in the tarball.  I suspect I'm missing some other cuda package?

Thanks.

**Comment by agontarek** [comment]
We currently publish the following instructions in the top level README:
```
CUDA-GDB BUILD INSTRUCTIONS (example only, adjust as needed)
===========================

First, make sure that libtermcap and other required dependent packages are 
installed (try sudo yum install ncurses-devel). The configure command will
issue an error if some packages are missing.

Please note that the libexpat development headers must be present if cuda-gdb
is to be used for cross-platform debugging.

Issue the following commands to build cuda-gdb:
    ./configure --program-prefix=cuda- \
        --enable-cuda \
        --enable-targets="x86_64-unknown-linux-gnu,\
        arm-elf-linux-gnu,m68k-unknown-linux-gnu" \
        CFLAGS='-I/usr/local/cuda/include' \
        LDFLAGS='-lpthread'
    make
```
As a workaround, please pass the following flags:
```
CFLAGS="-I/usr/local/cuda/extras/Debugger/include/ -I/usr/local/cuda/include" \
CXXFLAGS="-I/usr/local/cuda/extras/Debugger/include/ -I/usr/local/cuda/include" \
```
Also use the target `make all-gdb` to build cuda-gdb source.

These discrepancies will be addressed in a future release.

**Comment by epasveer** [comment]
Many Thanks!   I'll try it out.

**Comment by cyxu0401** [comment]
> Many Thanks! I'll try it out.

Hi, I encountered the same error, but the modified commands do not work. Have you solved the problem?

**Comment by epasveer** [comment]
To be honest, it's been so long that I don't know.  I've moved on to other things.

I'll check it out again this weekend coming up.

**Comment by epasveer** [comment]
There's a new cuda-gdb 12.3 release, but it has the same problem.

Here's what I did to get it to compile.  Basically what @agontarek  said.

First, this task was originally for 12.2. I'm now trying 12.3.  There's cuda 12.4 out there but there's no cuda-gdb 12.4 release yet. So I'm using cuda-12.3 and cuda-gdb-12.3.   

Here's my build commands. Note, it points to the cuda-12.3 installation directory that you should have built earlier. It has the missing header file.

```
$ ./configure --program-prefix=cuda- \
    --prefix=/usr/local/cuda \
    --enable-cuda \
    --enable-targets="x86_64-unknown-linux-gnu,arm-elf-linux-gnu,m68k-unknown-linux-gnu" \
    CFLAGS="-I/usr/local/cuda-12.3/extras/Debugger/include/ -I/usr/local/cuda-12.3/include" \
    CXXFLAGS="-I/usr/local/cuda-12.3/extras/Debugger/include/ -I/usr/local/cuda-12.3/include" \
    LDFLAGS='-lpthread'

$ make all-gdb
$ sudo make install
```

**Comment by agontarek** [comment]
The 12.4 release has been made available on github. The cudadebugger.h header file is distributed with the CUDA Toolkit. The CUDA Toolkit matching the cuda-gdb release should be used when building cuda-gdb.

**Comment by epasveer** [comment]
Thanks @agontarek.

I'll try it in the next couple days.

**Comment by epasveer** [comment]
Hi,

I got around to trying version 12.4.  Things went smoothly up until I the "sudo make install".  I got this.
```
$ sudo make install
...
make[3]: Leaving directory '/nas/erniep/Development/cuda-gdb/cuda-gdb-cuda-toolkit-12.4-release/opcodes/po'
make[2]: Leaving directory '/nas/erniep/Development/cuda-gdb/cuda-gdb-cuda-toolkit-12.4-release/opcodes'
make[2]: Entering directory '/nas/erniep/Development/cuda-gdb/cuda-gdb-cuda-toolkit-12.4-release/binutils'
make[2]: *** No rule to make target 'install'.  Stop.
make[2]: Leaving directory '/nas/erniep/Development/cuda-gdb/cuda-gdb-cuda-toolkit-12.4-release/binutils'
make[1]: *** [Makefile:4170: install-binutils] Error 2
make[1]: Leaving directory '/nas/erniep/Development/cuda-gdb/cuda-gdb-cuda-toolkit-12.4-release'
make: *** [Makefile:2599: install] Error 2
```

This works, however,
```
$ sudo make install-gdb
.... lots of normal looking output...
```
And my destination folder looks good.
```
erniep@gracie:(cuda-gdb-cuda-toolkit-12.4-release)$ ls -ltr /usr/local/cuda/bin/cuda*
-rwxr-xr-x 1 root root 25204848 Mar 17 12:31 /usr/local/cuda/bin/cuda-gdb
-rwxr-xr-x 1 root root     3541 Mar 17 12:31 /usr/local/cuda/bin/cuda-gcore
-rwxr-xr-x 1 root root     4627 Mar 17 12:31 /usr/local/cuda/bin/cuda-gdb-add-index
```

**Comment by epasveer** [comment]
I just noticed it didn't make "cuda-gdbserver".  These instructions work better.
```
$ ./configure --program-prefix=cuda- \
    --prefix=/usr/local/cuda \
    --enable-cuda \
    --enable-targets="x86_64-unknown-linux-gnu,arm-elf-linux-gnu,m68k-unknown-linux-gnu" \
    CFLAGS="-I/usr/local/cuda-12.4/extras/Debugger/include/ -I/usr/local/cuda-12.4/include" \
    CXXFLAGS="-I/usr/local/cuda-12.4/extras/Debugger/include/ -I/usr/local/cuda-12.4/include" \
    LDFLAGS='-lpthread'

$ make all-gdb all-gdbserver
$ sudo make install-gdb install-gdbserver
```
```

**Comment by epasveer** [comment]
As far as I'm concerned, this task can be closed.

**Comment by aideveloperme** [comment]
I'm facing the below error  while building cuda-gdb from source
code.
cuda driver  -12.5 version 
cudagdb verison 12.6 
gcc -12 



error-1: ../../gdb/cuda/libcudbg.c:2741:1: error: too many initializers for
‘const CUDBGAPI_st’
2741 | };
| ^
error-2:
../../gdb/cuda/cuda-api.c: In static member function ‘static bool
cuda_debugapi::execute_internal_command(const char*, char*, uint32_t)’:
../../gdb/cuda/cuda-api.c:2008:44: error: ‘const struct CUDBGAPI_st’ has no
member named ‘executeInternalCommand’
2008 | CUDBGResult res = m_instance.m_cudbgAPI->executeInternalCommand (command,
resultBuffer, sizeInBytes);
| ^~~~~~~~~~~~~~~~~~~~~~

**Comment by epasveer** [comment]
I'm pretty sure the cuda driver version should match the cuda gdb version.

**Comment by agontarek** [comment]
+1 The issue here is that a mismatched cudadebugger.h (which is released with the CTK) is being used with a different cuda-gdb release. We used to have guards to provide compiling with older debugger interfaces but removed that mechanism a few releases back. We will investigate either adding those back in or having a better mechanism for defining the debugger API interface.

**Comment by aideveloperme** [comment]
Issue with cuda-gdb related to the architecture registration, 
nvidia driver -550 
CTK Ver=12.6 
cudagdb -12.6 
 
nvidia driver -550 
CTK-12.5
CUDAGDB - 12.5 

after installing two versions of cuda-gdb 12.6 & 12.5 , i got the same issues in both the version 
cuda-gdb --version
../../gdb/arch-utils.c:1292: internal-error: gdbarch: Attempt to register unknown architecture (2)
A problem internal to GDB has been detected,
further debugging may prove unreliable.
----- Backtrace -----
0x51c80c ???
0x51c8af ???
0xaea23e ???
0xaea5f9 ???
0xcac8be ???
0x4a2ed0 ???
0x6901bb ???
0xb26542 ???
0xa9b40d ???
0x8c2c77 ???
0x8c39c9 ???
0x8c3a34 ???
0x411808 ???
0x7f02af374554 ???
0x411718 ???
0xffffffffffffffff ???
---------------------

This is a bug, please report it.  For instructions, see:
<https://www.gnu.org/software/gdb/bugs/>.

Aborted (core dumped)
