### ISSUE TITLE
install: cannot stat 'arm/run': No such file or directory

### ISSUE THREAD

**Issue by dmikushin** [NVIDIA/cuda-gdb#16]
Upon the installation of the [latest release](https://github.com/NVIDIA/cuda-gdb/releases/tag/cuda-toolkit-12.4-release) built from source:

```
libtool: install: /usr/bin/install -c arm/run /usr/local/cuda-gdb-tui/bin/cuda-run-tui-arm
install: cannot stat 'arm/run': No such file or directory
```

Is it normal that the simulator targets are broken?

**Comment by agontarek** [comment]
This is a known issue. Try passing `--disable-sim` to your configure line.
