### ISSUE TITLE
PTX debug_loc label handling

### ISSUE THREAD

**Issue by willghatch** [NVIDIA/cuda-gdb#21]
Hi, this may not be the right place to put this, so if there is a better place please let me know.

I'm working on LLVM backend support for debugging PTX.  The [PTX ISA docs](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#debugging-directives-section) say that you can have lines like `.b64 label1-label2`, and that that's been supported since ISA version 7.5.  I'm generating code like that, but when I try to run it, `cuModuleLoad` returns `0xda (INVALID_PTX)`.  When I run it through `ptxas` I get label errors.

More concretely, here is first part of a .debug_loc section I'm generating:

```
    .section    .debug_loc
        {
        $L__debug_loc0:
        .b64 $L__tmp0-$L__func_begin0
        .b64 $L__tmp3-$L__func_begin0
        .b8 7                                   // Loc expr size
        .b8 0
        .b8 144                                 // DW_OP_regx
        .b8 176                                 // 160832958768
        .b8 226                                 //
        .b8 144                                 //
        .b8 147                                 //
        .b8 215                                 //
        .b8 4                                   //
        .b64 0
        .b64 0
        $L__debug_loc1:
        .b64 $L__tmp1-$L__func_begin0
        .b64 $L__tmp3-$L__func_begin0
        .b8 6                                   // Loc expr size
        .b8 0
        .b8 144                                 // DW_OP_regx
        .b8 177                                 // 628253745
        .b8 200                                 //
        .b8 201                                 //
        .b8 171                                 //
        .b8 2                                   //
        .b64 0
        .b64 0
...
```

When I put the file through `ptxas`, I get:

```
ptxas error   : label '$L__tmp0' invalid
ptxas error   : label '$L__func_begin0' invalid
ptxas error   : label '$L__tmp3' invalid
ptxas error   : label '$L__func_begin0' invalid
ptxas error   : label '$L__tmp1' invalid
ptxas error   : label '$L__func_begin0' invalid
ptxas error   : label '$L__tmp3' invalid
ptxas error   : label '$L__func_begin0' invalid
...
```

All of the labels that it says are invalid are labels in the main code section of the PTX file, in the same function.  I've also tried running ptxas on PTX generated by nvcc, but editing the .debug_loc section to subtract labels like in the above example, and I get the same errors.  Is label subtraction not actually supported?  Or is there some special care that needs to be taken?

I've been trying this with ptxas version 12.5, using `.version 8.1` and `.version 8.5` PTX files.

Additionally, since PTX files generated by `nvcc` seem to just have the function labels and no subtraction of the `$L__func_begin0` label, thinking that maybe it's ultimately a zero label, I tried just generating the first label and omitting the subtraction.  But then `cuda-gdb` tells me that the values have been optimized out, and looking at the `pc` values vs the high and low values generated by the labels the `pc` at locations that should be covered by the generated ranges have wildly different `pc` values than the label range.  (Eg. I get range low value of 281469042581408 where a pc that is in the range where I expect to see the variable is 140734521290240.)

Any info about this would be awesome.  Thanks!

**Comment by agontarek** [comment]
Please check with the Nvidia compiler team by filing a forum topic here: https://forums.developer.nvidia.com/c/accelerated-computing/cuda/cuda-nvcc-compiler

**Comment by willghatch** [comment]
Thanks, by the way!  I ultimately worked around it, but I should still post there, as at least the documentation should be improved.
