### ISSUE TITLE
Assertion in switch_to_thread_1 with GDB Testsuite forking-threads-plus-breakpoint.exp

### ISSUE THREAD

**Issue by louspe-linaro** [NVIDIA/cuda-gdb#9]
This issue is an intermittent flake - failing on both aarch64 and amd64 - but not everytime the testsuite it run.

To reproduce
```
make check-gdb RUNTESTFLAGS="--target_board=cuda forking-threads-plus-breakpoint.exp GDB=/usr/local/cuda-12.0/bin/cuda-gdb"
```
where cuda.exp is a board file containing:
```
set_board_info gdb_prompt "\\(cuda-gdb\\)"
```
With GCC 12.1.0.

When checking in `gdb/testsuite/gdb.log`, the following assertion can be found in the log file:
```
/home/user/cuda-gdb-120-source/gdb/thread.c:1403: internal-error: switch_to_thread_1: Assertion `thr != NULL' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
```

This seems to relate to the changes in CUDA GDB relating to `switch_to_thread`

**Comment by agontarek** [comment]
A fix for this will be included with the next CTK release.
